name: pilot_json_serialization
description: json_serialization

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^2.0.0

  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true
