name: ui_challenges
description: UI challenges

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/flat_design_inspiration/

  uses-material-design: true
